### ISSUE TITLE
Cura fails to run on 18.04

### ISSUE THREAD

**Issue by battlezone** [thopiekar/Cura-packaging#54]
I just installed Cura via your PPA, but when I start it, nothing shows up.
When running it from terminal I get the following:
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/cura/CrashHandler.py", line 21, in <module>
    from UM.Application import Application
  File "/usr/lib/python3/dist-packages/UM/Application.py", line 15, in <module>
    from UM.Settings.ContainerRegistry import ContainerRegistry
  File "/usr/lib/python3/dist-packages/UM/Settings/ContainerRegistry.py", line 36, in <module>
    import UM.Qt.QtApplication
  File "/usr/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 15, in <module>
    from UM.FileHandler.ReadFileJob import ReadFileJob
  File "/usr/lib/python3/dist-packages/UM/FileHandler/ReadFileJob.py", line 5, in <module>
    from UM.Application import Application
ImportError: cannot import name 'Application'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/cura", line 135, in <module>
    from cura.CuraApplication import CuraApplication
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 16, in <module>
    from UM.Application import Application
  File "/usr/lib/python3/dist-packages/UM/Application.py", line 15, in <module>
    from UM.Settings.ContainerRegistry import ContainerRegistry
  File "/usr/lib/python3/dist-packages/UM/Settings/ContainerRegistry.py", line 36, in <module>
    import UM.Qt.QtApplication
  File "/usr/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 15, in <module>
    from UM.FileHandler.ReadFileJob import ReadFileJob
  File "/usr/lib/python3/dist-packages/UM/FileHandler/ReadFileJob.py", line 5, in <module>
    from UM.Application import Application
ImportError: cannot import name 'Application'
```

This is both the case for cura and cura-master PPA

**Comment by thopiekar** [comment]
Think I found the problem.
Let's see..

**Comment by thopiekar** [comment]
Can you try again? Thanks!

**Comment by battlezone** [comment]
Still not working. Same error.

**Comment by battlezone** [comment]
It seems there was a delay with updating the ppa. I noticed there was a cura update on saturday/sunday and it's indeed working fine now. Thank you!

**Comment by thopiekar** [comment]
Haha, was only experimenting this day. Actually thought that I ended up
with the same problem. But great to hear that it works.
I won't touch the stable PPA anymore then 😂
